# Generated by Django 4.2.1 on 2023-05-15 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.CharField(choices=[('Musique', 'Musique'), ('Sport', 'Sport'), ('Cinema', 'Cinema')], max_length=10)),
                ('state', models.BooleanField(default=False)),
                ('nbe_participant', models.IntegerField(default=0)),
                ('evt_date', models.DateTimeField(null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('evt_date__gte', datetime.datetime(2023, 5, 15, 13, 39, 8, 252518))), name='Please check out the event date'),
        ),
    ]
