# Generated by Django 4.2.1 on 2023-05-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'personne'},
        ),
    ]
